apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ikea"
  namespace: "scanner"
  labels:
    app: "frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend"
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
        - name: "ikea"
          image: "010438494499.dkr.ecr.us-east-1.amazonaws.com/kube:xyz"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      tolerations:
        - key: "name"
          operator: "Equal"
          value: "frontend_group"
          effect: "NoSchedule"
